package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ALTER_PWD_INFO.
 */
public class AlterPwdInfo {

    private String userId;
    private String oldpassword;
    private String newpassword;
    private String ssid;

    public AlterPwdInfo() {
    }

    public AlterPwdInfo(String userId) {
        this.userId = userId;
    }

    public AlterPwdInfo(String userId, String oldpassword, String newpassword, String ssid) {
        this.userId = userId;
        this.oldpassword = oldpassword;
        this.newpassword = newpassword;
        this.ssid = ssid;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getOldpassword() {
        return oldpassword;
    }

    public void setOldpassword(String oldpassword) {
        this.oldpassword = oldpassword;
    }

    public String getNewpassword() {
        return newpassword;
    }

    public void setNewpassword(String newpassword) {
        this.newpassword = newpassword;
    }

    public String getSsid() {
        return ssid;
    }

    public void setSsid(String ssid) {
        this.ssid = ssid;
    }

}
