package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APK_UPDATE_INFO.
 */
public class ApkUpdateInfo {

    private String id;
    private String appUrl;
    private String apkName;
    private String appId;
    private String description;
    private String name;
    private String useFlag;
    private String versionCode;
    private String versionName;
    private String uploadTime;
    private String packName;
    private String apkSize;

    public ApkUpdateInfo() {
    }

    public ApkUpdateInfo(String id) {
        this.id = id;
    }

    public ApkUpdateInfo(String id, String appUrl, String apkName, String appId, String description, String name, String useFlag, String versionCode, String versionName, String uploadTime, String packName, String apkSize) {
        this.id = id;
        this.appUrl = appUrl;
        this.apkName = apkName;
        this.appId = appId;
        this.description = description;
        this.name = name;
        this.useFlag = useFlag;
        this.versionCode = versionCode;
        this.versionName = versionName;
        this.uploadTime = uploadTime;
        this.packName = packName;
        this.apkSize = apkSize;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAppUrl() {
        return appUrl;
    }

    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl;
    }

    public String getApkName() {
        return apkName;
    }

    public void setApkName(String apkName) {
        this.apkName = apkName;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUseFlag() {
        return useFlag;
    }

    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    public String getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public String getUploadTime() {
        return uploadTime;
    }

    public void setUploadTime(String uploadTime) {
        this.uploadTime = uploadTime;
    }

    public String getPackName() {
        return packName;
    }

    public void setPackName(String packName) {
        this.packName = packName;
    }

    public String getApkSize() {
        return apkSize;
    }

    public void setApkSize(String apkSize) {
        this.apkSize = apkSize;
    }

}
