package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table AUDIT_INFO.
 */
public class AuditInfo {

    private String name;
    private String ziliao;
    private String counts;

    public AuditInfo() {
    }

    public AuditInfo(String name) {
        this.name = name;
    }

    public AuditInfo(String name, String ziliao, String counts) {
        this.name = name;
        this.ziliao = ziliao;
        this.counts = counts;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getZiliao() {
        return ziliao;
    }

    public void setZiliao(String ziliao) {
        this.ziliao = ziliao;
    }

    public String getCounts() {
        return counts;
    }

    public void setCounts(String counts) {
        this.counts = counts;
    }

}
