package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMPANY_LOGO_INFO.
 */
public class CompanyLogoInfo {

    private String id;
    private String logopath;

    public CompanyLogoInfo() {
    }

    public CompanyLogoInfo(String id) {
        this.id = id;
    }

    public CompanyLogoInfo(String id, String logopath) {
        this.id = id;
        this.logopath = logopath;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getLogopath() {
        return logopath;
    }

    public void setLogopath(String logopath) {
        this.logopath = logopath;
    }

}
