package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CRAFT_INFO.
 */
public class CraftInfo {

    private String infoimg;

    public CraftInfo() {
    }

    public CraftInfo(String infoimg) {
        this.infoimg = infoimg;
    }

    public String getInfoimg() {
        return infoimg;
    }

    public void setInfoimg(String infoimg) {
        this.infoimg = infoimg;
    }

}
