package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DAN_DIAN_LOGIN_PUB.
 */
public class DanDianLoginPub {

    private String name;
    private String status;
    private String num;
    private String pageno;

    public DanDianLoginPub() {
    }

    public DanDianLoginPub(String name) {
        this.name = name;
    }

    public DanDianLoginPub(String name, String status, String num, String pageno) {
        this.name = name;
        this.status = status;
        this.num = num;
        this.pageno = pageno;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    public String getPageno() {
        return pageno;
    }

    public void setPageno(String pageno) {
        this.pageno = pageno;
    }

}
