package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEAL_INFO.
 */
public class DealInfo {

    private String handledesc;
    private String status;
    private String dealuser;
    private String warndealtime;

    public DealInfo() {
    }

    public DealInfo(String handledesc) {
        this.handledesc = handledesc;
    }

    public DealInfo(String handledesc, String status, String dealuser, String warndealtime) {
        this.handledesc = handledesc;
        this.status = status;
        this.dealuser = dealuser;
        this.warndealtime = warndealtime;
    }

    public String getHandledesc() {
        return handledesc;
    }

    public void setHandledesc(String handledesc) {
        this.handledesc = handledesc;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDealuser() {
        return dealuser;
    }

    public void setDealuser(String dealuser) {
        this.dealuser = dealuser;
    }

    public String getWarndealtime() {
        return warndealtime;
    }

    public void setWarndealtime(String warndealtime) {
        this.warndealtime = warndealtime;
    }

}
