package newsemc.com.awit.news.newsemcapp.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import newsemc.com.awit.news.newsemcapp.dao.DepartmentInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DEPARTMENT_INFO.
*/
public class DepartmentInfoDao extends AbstractDao<DepartmentInfo, Void> {

    public static final String TABLENAME = "DEPARTMENT_INFO";

    /**
     * Properties of entity DepartmentInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Duty = new Property(2, String.class, "duty", false, "DUTY");
        public final static Property F_userId = new Property(3, String.class, "f_userId", false, "F_USER_ID");
    };

    private DaoSession daoSession;

    private Query<DepartmentInfo> personInfo_DepartmentInfoListQuery;

    public DepartmentInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DepartmentInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DEPARTMENT_INFO' (" + //
                "'ID' TEXT," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'DUTY' TEXT," + // 2: duty
                "'F_USER_ID' TEXT NOT NULL );"); // 3: f_userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DEPARTMENT_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DepartmentInfo entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String duty = entity.getDuty();
        if (duty != null) {
            stmt.bindString(3, duty);
        }
        stmt.bindString(4, entity.getF_userId());
    }

    @Override
    protected void attachEntity(DepartmentInfo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public DepartmentInfo readEntity(Cursor cursor, int offset) {
        DepartmentInfo entity = new DepartmentInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // duty
            cursor.getString(offset + 3) // f_userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DepartmentInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDuty(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setF_userId(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(DepartmentInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(DepartmentInfo entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "departmentInfoList" to-many relationship of PersonInfo. */
    public List<DepartmentInfo> _queryPersonInfo_DepartmentInfoList(String f_userId) {
        synchronized (this) {
            if (personInfo_DepartmentInfoListQuery == null) {
                QueryBuilder<DepartmentInfo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.F_userId.eq(null));
                personInfo_DepartmentInfoListQuery = queryBuilder.build();
            }
        }
        Query<DepartmentInfo> query = personInfo_DepartmentInfoListQuery.forCurrentThread();
        query.setParameter(0, f_userId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPersonInfoDao().getAllColumns());
            builder.append(" FROM DEPARTMENT_INFO T");
            builder.append(" LEFT JOIN PERSON_INFO T0 ON T.'F_USER_ID'=T0.'USER_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DepartmentInfo loadCurrentDeep(Cursor cursor, boolean lock) {
        DepartmentInfo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PersonInfo personInfo = loadCurrentOther(daoSession.getPersonInfoDao(), cursor, offset);
         if(personInfo != null) {
            entity.setPersonInfo(personInfo);
        }

        return entity;    
    }

    public DepartmentInfo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DepartmentInfo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DepartmentInfo> list = new ArrayList<DepartmentInfo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DepartmentInfo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DepartmentInfo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
