package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DETAIL_INFO.
 */
public class DetailInfo {

    private String infoid;
    private String infotype;
    private String htmlpath;
    private String num;

    public DetailInfo() {
    }

    public DetailInfo(String infoid) {
        this.infoid = infoid;
    }

    public DetailInfo(String infoid, String infotype, String htmlpath, String num) {
        this.infoid = infoid;
        this.infotype = infotype;
        this.htmlpath = htmlpath;
        this.num = num;
    }

    public String getInfoid() {
        return infoid;
    }

    public void setInfoid(String infoid) {
        this.infoid = infoid;
    }

    public String getInfotype() {
        return infotype;
    }

    public void setInfotype(String infotype) {
        this.infotype = infotype;
    }

    public String getHtmlpath() {
        return htmlpath;
    }

    public void setHtmlpath(String htmlpath) {
        this.htmlpath = htmlpath;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

}
