package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ICON_INFO.
 */
public class IconInfo {

    private Integer id;
    private String status;
    private String name;
    private String type;
    private String pageno;

    public IconInfo() {
    }

    public IconInfo(Integer id) {
        this.id = id;
    }

    public IconInfo(Integer id, String status, String name, String type, String pageno) {
        this.id = id;
        this.status = status;
        this.name = name;
        this.type = type;
        this.pageno = pageno;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPageno() {
        return pageno;
    }

    public void setPageno(String pageno) {
        this.pageno = pageno;
    }

}
