package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE_INFO.
 */
public class ImageInfo {

    private String infoid;
    private String infotype;
    private String infoname;
    private String infoimg;
    private String infourl;
    private String infocontent;
    private String num;
    private String pageno;
    private String infodate;

    public void setSource(String source) {
        this.source = source;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    private String source;

    public String getPublisher() {
        return publisher;
    }

    public String getSource() {
        return source;
    }

    private String publisher;

    public String getIsnew() {
        return isnew;
    }

    public void setIsnew(String isnew) {
        this.isnew = isnew;
    }

    private String isnew;

    public ImageInfo() {
    }

    public ImageInfo(String infoid) {
        this.infoid = infoid;
    }

    public ImageInfo(String infoid, String infotype, String infoname, String infoimg, String infourl, String infocontent, String num, String pageno, String infodate,String source,String publisher,String isnew) {
        this.infoid = infoid;
        this.infotype = infotype;
        this.infoname = infoname;
        this.infoimg = infoimg;
        this.infourl = infourl;
        this.infocontent = infocontent;
        this.num = num;
        this.pageno = pageno;
        this.infodate = infodate;
        this.source = source;
        this.publisher = publisher;
        this.isnew = isnew;
    }

    public String getInfoid() {
        return infoid;
    }

    public void setInfoid(String infoid) {
        this.infoid = infoid;
    }

    public String getInfotype() {
        return infotype;
    }

    public void setInfotype(String infotype) {
        this.infotype = infotype;
    }

    public String getInfoname() {
        return infoname;
    }

    public void setInfoname(String infoname) {
        this.infoname = infoname;
    }

    public String getInfoimg() {
        return infoimg;
    }

    public void setInfoimg(String infoimg) {
        this.infoimg = infoimg;
    }

    public String getInfourl() {
        return infourl;
    }

    public void setInfourl(String infourl) {
        this.infourl = infourl;
    }

    public String getInfocontent() {
        return infocontent;
    }

    public void setInfocontent(String infocontent) {
        this.infocontent = infocontent;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    public String getPageno() {
        return pageno;
    }

    public void setPageno(String pageno) {
        this.pageno = pageno;
    }

    public String getInfodate() {
        return infodate;
    }

    public void setInfodate(String infodate) {
        this.infodate = infodate;
    }

}
