package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LAB_INFO.
 */
public class LabInfo {

    private String sectionname;
    private String yljtotal;
    private String yljusenum;
    private String wnjtotal;
    private String wnjusenum;
    private String reporttotal;
    private String hntinfo;
    private String gjinfo;
    private String gjhjinfo;
    private String gjjxinfo;

    public LabInfo() {
    }

    public LabInfo(String sectionname) {
        this.sectionname = sectionname;
    }

    public LabInfo(String sectionname, String yljtotal, String yljusenum, String wnjtotal, String wnjusenum, String reporttotal, String hntinfo, String gjinfo, String gjhjinfo, String gjjxinfo) {
        this.sectionname = sectionname;
        this.yljtotal = yljtotal;
        this.yljusenum = yljusenum;
        this.wnjtotal = wnjtotal;
        this.wnjusenum = wnjusenum;
        this.reporttotal = reporttotal;
        this.hntinfo = hntinfo;
        this.gjinfo = gjinfo;
        this.gjhjinfo = gjhjinfo;
        this.gjjxinfo = gjjxinfo;
    }

    public String getSectionname() {
        return sectionname;
    }

    public void setSectionname(String sectionname) {
        this.sectionname = sectionname;
    }

    public String getYljtotal() {
        return yljtotal;
    }

    public void setYljtotal(String yljtotal) {
        this.yljtotal = yljtotal;
    }

    public String getYljusenum() {
        return yljusenum;
    }

    public void setYljusenum(String yljusenum) {
        this.yljusenum = yljusenum;
    }

    public String getWnjtotal() {
        return wnjtotal;
    }

    public void setWnjtotal(String wnjtotal) {
        this.wnjtotal = wnjtotal;
    }

    public String getWnjusenum() {
        return wnjusenum;
    }

    public void setWnjusenum(String wnjusenum) {
        this.wnjusenum = wnjusenum;
    }

    public String getReporttotal() {
        return reporttotal;
    }

    public void setReporttotal(String reporttotal) {
        this.reporttotal = reporttotal;
    }

    public String getHntinfo() {
        return hntinfo;
    }

    public void setHntinfo(String hntinfo) {
        this.hntinfo = hntinfo;
    }

    public String getGjinfo() {
        return gjinfo;
    }

    public void setGjinfo(String gjinfo) {
        this.gjinfo = gjinfo;
    }

    public String getGjhjinfo() {
        return gjhjinfo;
    }

    public void setGjhjinfo(String gjhjinfo) {
        this.gjhjinfo = gjhjinfo;
    }

    public String getGjjxinfo() {
        return gjjxinfo;
    }

    public void setGjjxinfo(String gjjxinfo) {
        this.gjjxinfo = gjjxinfo;
    }

}
