package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LXL_BXO_INFO.
 */
public class LxlBxoInfo {

    private String prosectionid;
    private String prosectionname;
    private String prositename;
    private String pointname;
    private String sgjd;
    private String warnrecord;
    private String buildname;
    private String chargename;
    private String flow;

    public LxlBxoInfo() {
    }

    public LxlBxoInfo(String prosectionid) {
        this.prosectionid = prosectionid;
    }

    public LxlBxoInfo(String prosectionid, String prosectionname, String prositename, String pointname, String sgjd, String warnrecord, String buildname, String chargename, String flow) {
        this.prosectionid = prosectionid;
        this.prosectionname = prosectionname;
        this.prositename = prositename;
        this.pointname = pointname;
        this.sgjd = sgjd;
        this.warnrecord = warnrecord;
        this.buildname = buildname;
        this.chargename = chargename;
        this.flow = flow;
    }

    public String getProsectionid() {
        return prosectionid;
    }

    public void setProsectionid(String prosectionid) {
        this.prosectionid = prosectionid;
    }

    public String getProsectionname() {
        return prosectionname;
    }

    public void setProsectionname(String prosectionname) {
        this.prosectionname = prosectionname;
    }

    public String getPrositename() {
        return prositename;
    }

    public void setPrositename(String prositename) {
        this.prositename = prositename;
    }

    public String getPointname() {
        return pointname;
    }

    public void setPointname(String pointname) {
        this.pointname = pointname;
    }

    public String getSgjd() {
        return sgjd;
    }

    public void setSgjd(String sgjd) {
        this.sgjd = sgjd;
    }

    public String getWarnrecord() {
        return warnrecord;
    }

    public void setWarnrecord(String warnrecord) {
        this.warnrecord = warnrecord;
    }

    public String getBuildname() {
        return buildname;
    }

    public void setBuildname(String buildname) {
        this.buildname = buildname;
    }

    public String getChargename() {
        return chargename;
    }

    public void setChargename(String chargename) {
        this.chargename = chargename;
    }

    public String getFlow() {
        return flow;
    }

    public void setFlow(String flow) {
        this.flow = flow;
    }

}
