package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEASURE_DETAIL_INFO.
 */
public class MeasureDetailInfo {

    private String id;
    private String name;
    private String monitorobjectname;
    private String peak;
    private String speed;
    private String warntime;
    private String warnlevel;
    private String dealflag;

    public MeasureDetailInfo() {
    }

    public MeasureDetailInfo(String id) {
        this.id = id;
    }

    public MeasureDetailInfo(String id, String name, String monitorobjectname, String peak, String speed, String warntime, String warnlevel, String dealflag) {
        this.id = id;
        this.name = name;
        this.monitorobjectname = monitorobjectname;
        this.peak = peak;
        this.speed = speed;
        this.warntime = warntime;
        this.warnlevel = warnlevel;
        this.dealflag = dealflag;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMonitorobjectname() {
        return monitorobjectname;
    }

    public void setMonitorobjectname(String monitorobjectname) {
        this.monitorobjectname = monitorobjectname;
    }

    public String getPeak() {
        return peak;
    }

    public void setPeak(String peak) {
        this.peak = peak;
    }

    public String getSpeed() {
        return speed;
    }

    public void setSpeed(String speed) {
        this.speed = speed;
    }

    public String getWarntime() {
        return warntime;
    }

    public void setWarntime(String warntime) {
        this.warntime = warntime;
    }

    public String getWarnlevel() {
        return warnlevel;
    }

    public void setWarnlevel(String warnlevel) {
        this.warnlevel = warnlevel;
    }

    public String getDealflag() {
        return dealflag;
    }

    public void setDealflag(String dealflag) {
        this.dealflag = dealflag;
    }

}
