package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLAN_INFO.
 */
public class PlanInfo {

    private String projectnam;
    private String yongkaiper;
    private String linkaiper;
    private String chaikaiper;
    private String man;
    private String tel;

    public PlanInfo() {
    }

    public PlanInfo(String projectnam) {
        this.projectnam = projectnam;
    }

    public PlanInfo(String projectnam, String yongkaiper, String linkaiper, String chaikaiper, String man, String tel) {
        this.projectnam = projectnam;
        this.yongkaiper = yongkaiper;
        this.linkaiper = linkaiper;
        this.chaikaiper = chaikaiper;
        this.man = man;
        this.tel = tel;
    }

    public String getProjectnam() {
        return projectnam;
    }

    public void setProjectnam(String projectnam) {
        this.projectnam = projectnam;
    }

    public String getYongkaiper() {
        return yongkaiper;
    }

    public void setYongkaiper(String yongkaiper) {
        this.yongkaiper = yongkaiper;
    }

    public String getLinkaiper() {
        return linkaiper;
    }

    public void setLinkaiper(String linkaiper) {
        this.linkaiper = linkaiper;
    }

    public String getChaikaiper() {
        return chaikaiper;
    }

    public void setChaikaiper(String chaikaiper) {
        this.chaikaiper = chaikaiper;
    }

    public String getMan() {
        return man;
    }

    public void setMan(String man) {
        this.man = man;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

}
