package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRECEPT_INFO.
 */
public class PreceptInfo {

    private String id;
    private String huiyiname;
    private String danwei;
    private String jiyao;
    private String huiyitime;

    public PreceptInfo() {
    }

    public PreceptInfo(String id) {
        this.id = id;
    }

    public PreceptInfo(String id, String huiyiname, String danwei, String jiyao, String huiyitime) {
        this.id = id;
        this.huiyiname = huiyiname;
        this.danwei = danwei;
        this.jiyao = jiyao;
        this.huiyitime = huiyitime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getHuiyiname() {
        return huiyiname;
    }

    public void setHuiyiname(String huiyiname) {
        this.huiyiname = huiyiname;
    }

    public String getDanwei() {
        return danwei;
    }

    public void setDanwei(String danwei) {
        this.danwei = danwei;
    }

    public String getJiyao() {
        return jiyao;
    }

    public void setJiyao(String jiyao) {
        this.jiyao = jiyao;
    }

    public String getHuiyitime() {
        return huiyitime;
    }

    public void setHuiyitime(String huiyitime) {
        this.huiyitime = huiyitime;
    }

}
