package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROJECT_TTRENDS_INFO.
 */
public class ProjectTtrendsInfo {

    private String id;
    private String name;
    private String code;
    private String conxname;
    private String aptitude;
    private String tenders;
    private String totallength;
    private String constractamount;
    private String projectinfoid;

    public ProjectTtrendsInfo() {
    }

    public ProjectTtrendsInfo(String id) {
        this.id = id;
    }

    public ProjectTtrendsInfo(String id, String name, String code, String conxname, String aptitude, String tenders, String totallength, String constractamount, String projectinfoid) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.conxname = conxname;
        this.aptitude = aptitude;
        this.tenders = tenders;
        this.totallength = totallength;
        this.constractamount = constractamount;
        this.projectinfoid = projectinfoid;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getConxname() {
        return conxname;
    }

    public void setConxname(String conxname) {
        this.conxname = conxname;
    }

    public String getAptitude() {
        return aptitude;
    }

    public void setAptitude(String aptitude) {
        this.aptitude = aptitude;
    }

    public String getTenders() {
        return tenders;
    }

    public void setTenders(String tenders) {
        this.tenders = tenders;
    }

    public String getTotallength() {
        return totallength;
    }

    public void setTotallength(String totallength) {
        this.totallength = totallength;
    }

    public String getConstractamount() {
        return constractamount;
    }

    public void setConstractamount(String constractamount) {
        this.constractamount = constractamount;
    }

    public String getProjectinfoid() {
        return projectinfoid;
    }

    public void setProjectinfoid(String projectinfoid) {
        this.projectinfoid = projectinfoid;
    }

}
