package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROJECT_IMPS_INFO.
 */
public class ProjectImpsInfo {

    private String projectname;
    private String name;
    private String lc;
    private String middl;
    private String sitelength;
    private String planopentime;
    private String planclosetime;

    public ProjectImpsInfo() {
    }

    public ProjectImpsInfo(String projectname) {
        this.projectname = projectname;
    }

    public ProjectImpsInfo(String projectname, String name, String lc, String middl, String sitelength, String planopentime, String planclosetime) {
        this.projectname = projectname;
        this.name = name;
        this.lc = lc;
        this.middl = middl;
        this.sitelength = sitelength;
        this.planopentime = planopentime;
        this.planclosetime = planclosetime;
    }

    public String getProjectname() {
        return projectname;
    }

    public void setProjectname(String projectname) {
        this.projectname = projectname;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLc() {
        return lc;
    }

    public void setLc(String lc) {
        this.lc = lc;
    }

    public String getMiddl() {
        return middl;
    }

    public void setMiddl(String middl) {
        this.middl = middl;
    }

    public String getSitelength() {
        return sitelength;
    }

    public void setSitelength(String sitelength) {
        this.sitelength = sitelength;
    }

    public String getPlanopentime() {
        return planopentime;
    }

    public void setPlanopentime(String planopentime) {
        this.planopentime = planopentime;
    }

    public String getPlanclosetime() {
        return planclosetime;
    }

    public void setPlanclosetime(String planclosetime) {
        this.planclosetime = planclosetime;
    }

}
