package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROJECT_INFO_DETAIL.
 */
public class ProjectInfoDetail {

    private String project_id;
    private String projectName;
    private String projectType;
    private String conxName;
    private String projectSource;
    private String projectCode;
    private String projectLength;
    private String startStation;
    private String stopStation;
    private String startDate;
    private String stopDate;
    private String stationNum;
    private String invest;
    private String startMile;
    private String stopMile;
    private String designCorpName;
    private String examineCorpName;
    private String proCity;
    private String proStation;
    private String description;

    public ProjectInfoDetail() {
    }

    public ProjectInfoDetail(String project_id) {
        this.project_id = project_id;
    }

    public ProjectInfoDetail(String project_id, String projectName, String projectType, String conxName, String projectSource, String projectCode, String projectLength, String startStation, String stopStation, String startDate, String stopDate, String stationNum, String invest, String startMile, String stopMile, String designCorpName, String examineCorpName, String proCity, String proStation, String description) {
        this.project_id = project_id;
        this.projectName = projectName;
        this.projectType = projectType;
        this.conxName = conxName;
        this.projectSource = projectSource;
        this.projectCode = projectCode;
        this.projectLength = projectLength;
        this.startStation = startStation;
        this.stopStation = stopStation;
        this.startDate = startDate;
        this.stopDate = stopDate;
        this.stationNum = stationNum;
        this.invest = invest;
        this.startMile = startMile;
        this.stopMile = stopMile;
        this.designCorpName = designCorpName;
        this.examineCorpName = examineCorpName;
        this.proCity = proCity;
        this.proStation = proStation;
        this.description = description;
    }

    public String getProject_id() {
        return project_id;
    }

    public void setProject_id(String project_id) {
        this.project_id = project_id;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getProjectType() {
        return projectType;
    }

    public void setProjectType(String projectType) {
        this.projectType = projectType;
    }

    public String getConxName() {
        return conxName;
    }

    public void setConxName(String conxName) {
        this.conxName = conxName;
    }

    public String getProjectSource() {
        return projectSource;
    }

    public void setProjectSource(String projectSource) {
        this.projectSource = projectSource;
    }

    public String getProjectCode() {
        return projectCode;
    }

    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    public String getProjectLength() {
        return projectLength;
    }

    public void setProjectLength(String projectLength) {
        this.projectLength = projectLength;
    }

    public String getStartStation() {
        return startStation;
    }

    public void setStartStation(String startStation) {
        this.startStation = startStation;
    }

    public String getStopStation() {
        return stopStation;
    }

    public void setStopStation(String stopStation) {
        this.stopStation = stopStation;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getStopDate() {
        return stopDate;
    }

    public void setStopDate(String stopDate) {
        this.stopDate = stopDate;
    }

    public String getStationNum() {
        return stationNum;
    }

    public void setStationNum(String stationNum) {
        this.stationNum = stationNum;
    }

    public String getInvest() {
        return invest;
    }

    public void setInvest(String invest) {
        this.invest = invest;
    }

    public String getStartMile() {
        return startMile;
    }

    public void setStartMile(String startMile) {
        this.startMile = startMile;
    }

    public String getStopMile() {
        return stopMile;
    }

    public void setStopMile(String stopMile) {
        this.stopMile = stopMile;
    }

    public String getDesignCorpName() {
        return designCorpName;
    }

    public void setDesignCorpName(String designCorpName) {
        this.designCorpName = designCorpName;
    }

    public String getExamineCorpName() {
        return examineCorpName;
    }

    public void setExamineCorpName(String examineCorpName) {
        this.examineCorpName = examineCorpName;
    }

    public String getProCity() {
        return proCity;
    }

    public void setProCity(String proCity) {
        this.proCity = proCity;
    }

    public String getProStation() {
        return proStation;
    }

    public void setProStation(String proStation) {
        this.proStation = proStation;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
