package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROJECT_INFO_DETAIL_PERIOD.
 */
public class ProjectInfoDetailPeriod {

    private String id;
    private String projectInfoId;
    private String jyWenhao;
    private String kyWenhao;
    private String csWenhao;
    private String sgWenhao;
    private String zdWenhao;
    private String sgJishu;
    private String sgTouzi;
    private String sgGongqi;
    private String szJdGongqi;

    public ProjectInfoDetailPeriod() {
    }

    public ProjectInfoDetailPeriod(String id, String projectInfoId, String jyWenhao, String kyWenhao, String csWenhao, String sgWenhao, String zdWenhao, String sgJishu, String sgTouzi, String sgGongqi, String szJdGongqi) {
        this.id = id;
        this.projectInfoId = projectInfoId;
        this.jyWenhao = jyWenhao;
        this.kyWenhao = kyWenhao;
        this.csWenhao = csWenhao;
        this.sgWenhao = sgWenhao;
        this.zdWenhao = zdWenhao;
        this.sgJishu = sgJishu;
        this.sgTouzi = sgTouzi;
        this.sgGongqi = sgGongqi;
        this.szJdGongqi = szJdGongqi;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProjectInfoId() {
        return projectInfoId;
    }

    public void setProjectInfoId(String projectInfoId) {
        this.projectInfoId = projectInfoId;
    }

    public String getJyWenhao() {
        return jyWenhao;
    }

    public void setJyWenhao(String jyWenhao) {
        this.jyWenhao = jyWenhao;
    }

    public String getKyWenhao() {
        return kyWenhao;
    }

    public void setKyWenhao(String kyWenhao) {
        this.kyWenhao = kyWenhao;
    }

    public String getCsWenhao() {
        return csWenhao;
    }

    public void setCsWenhao(String csWenhao) {
        this.csWenhao = csWenhao;
    }

    public String getSgWenhao() {
        return sgWenhao;
    }

    public void setSgWenhao(String sgWenhao) {
        this.sgWenhao = sgWenhao;
    }

    public String getZdWenhao() {
        return zdWenhao;
    }

    public void setZdWenhao(String zdWenhao) {
        this.zdWenhao = zdWenhao;
    }

    public String getSgJishu() {
        return sgJishu;
    }

    public void setSgJishu(String sgJishu) {
        this.sgJishu = sgJishu;
    }

    public String getSgTouzi() {
        return sgTouzi;
    }

    public void setSgTouzi(String sgTouzi) {
        this.sgTouzi = sgTouzi;
    }

    public String getSgGongqi() {
        return sgGongqi;
    }

    public void setSgGongqi(String sgGongqi) {
        this.sgGongqi = sgGongqi;
    }

    public String getSzJdGongqi() {
        return szJdGongqi;
    }

    public void setSzJdGongqi(String szJdGongqi) {
        this.szJdGongqi = szJdGongqi;
    }

}
