package newsemc.com.awit.news.newsemcapp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import newsemc.com.awit.news.newsemcapp.dao.ProjectInfoDetailPic;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PROJECT_INFO_DETAIL_PIC.
*/
public class ProjectInfoDetailPicDao extends AbstractDao<ProjectInfoDetailPic, String> {

    public static final String TABLENAME = "PROJECT_INFO_DETAIL_PIC";

    /**
     * Properties of entity ProjectInfoDetailPic.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ProjectPicName = new Property(0, String.class, "projectPicName", true, "PROJECT_PIC_NAME");
        public final static Property ProjectPicUrl = new Property(1, String.class, "projectPicUrl", false, "PROJECT_PIC_URL");
        public final static Property ProjectPicId = new Property(2, String.class, "projectPicId", false, "PROJECT_PIC_ID");
    };


    public ProjectInfoDetailPicDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectInfoDetailPicDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PROJECT_INFO_DETAIL_PIC' (" + //
                "'PROJECT_PIC_NAME' TEXT PRIMARY KEY NOT NULL ," + // 0: projectPicName
                "'PROJECT_PIC_URL' TEXT," + // 1: projectPicUrl
                "'PROJECT_PIC_ID' TEXT);"); // 2: projectPicId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PROJECT_INFO_DETAIL_PIC'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProjectInfoDetailPic entity) {
        stmt.clearBindings();
 
        String projectPicName = entity.getProjectPicName();
        if (projectPicName != null) {
            stmt.bindString(1, projectPicName);
        }
 
        String projectPicUrl = entity.getProjectPicUrl();
        if (projectPicUrl != null) {
            stmt.bindString(2, projectPicUrl);
        }
 
        String projectPicId = entity.getProjectPicId();
        if (projectPicId != null) {
            stmt.bindString(3, projectPicId);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ProjectInfoDetailPic readEntity(Cursor cursor, int offset) {
        ProjectInfoDetailPic entity = new ProjectInfoDetailPic( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // projectPicName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // projectPicUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // projectPicId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProjectInfoDetailPic entity, int offset) {
        entity.setProjectPicName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setProjectPicUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProjectPicId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(ProjectInfoDetailPic entity, long rowId) {
        return entity.getProjectPicName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(ProjectInfoDetailPic entity) {
        if(entity != null) {
            return entity.getProjectPicName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
