package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PUSH_INFO.
 */
public class PushInfo {

    private String wylcNum;
    private String oaNum;
    private String sum;

    public PushInfo() {
    }

    public PushInfo(String wylcNum) {
        this.wylcNum = wylcNum;
    }

    public PushInfo(String wylcNum, String oaNum, String sum) {
        this.wylcNum = wylcNum;
        this.oaNum = oaNum;
        this.sum = sum;
    }

    public String getWylcNum() {
        return wylcNum;
    }

    public void setWylcNum(String wylcNum) {
        this.wylcNum = wylcNum;
    }

    public String getOaNum() {
        return oaNum;
    }

    public void setOaNum(String oaNum) {
        this.oaNum = oaNum;
    }

    public String getSum() {
        return sum;
    }

    public void setSum(String sum) {
        this.sum = sum;
    }

}
