package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCIENCE_INFO.
 */
public class ScienceInfo {

    private String id;
    private String name;
    private String content;
    private String ctime;
    private String shedanwei;
    private String shidanwei;

    public ScienceInfo() {
    }

    public ScienceInfo(String id) {
        this.id = id;
    }

    public ScienceInfo(String id, String name, String content, String ctime, String shedanwei, String shidanwei) {
        this.id = id;
        this.name = name;
        this.content = content;
        this.ctime = ctime;
        this.shedanwei = shedanwei;
        this.shidanwei = shidanwei;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCtime() {
        return ctime;
    }

    public void setCtime(String ctime) {
        this.ctime = ctime;
    }

    public String getShedanwei() {
        return shedanwei;
    }

    public void setShedanwei(String shedanwei) {
        this.shedanwei = shedanwei;
    }

    public String getShidanwei() {
        return shidanwei;
    }

    public void setShidanwei(String shidanwei) {
        this.shidanwei = shidanwei;
    }

}
