package newsemc.com.awit.news.newsemcapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEDIMENTATION_INFO.
 */
public class SedimentationInfo {

    private String prosectionid;
    private String prosectionname;
    private String prositename;
    private String pointname;
    private String workinfo;
    private String msginfo;
    private String username;

    public SedimentationInfo() {
    }

    public SedimentationInfo(String prosectionid) {
        this.prosectionid = prosectionid;
    }

    public SedimentationInfo(String prosectionid, String prosectionname, String prositename, String pointname, String workinfo, String msginfo, String username) {
        this.prosectionid = prosectionid;
        this.prosectionname = prosectionname;
        this.prositename = prositename;
        this.pointname = pointname;
        this.workinfo = workinfo;
        this.msginfo = msginfo;
        this.username = username;
    }

    public String getProsectionid() {
        return prosectionid;
    }

    public void setProsectionid(String prosectionid) {
        this.prosectionid = prosectionid;
    }

    public String getProsectionname() {
        return prosectionname;
    }

    public void setProsectionname(String prosectionname) {
        this.prosectionname = prosectionname;
    }

    public String getPrositename() {
        return prositename;
    }

    public void setPrositename(String prositename) {
        this.prositename = prositename;
    }

    public String getPointname() {
        return pointname;
    }

    public void setPointname(String pointname) {
        this.pointname = pointname;
    }

    public String getWorkinfo() {
        return workinfo;
    }

    public void setWorkinfo(String workinfo) {
        this.workinfo = workinfo;
    }

    public String getMsginfo() {
        return msginfo;
    }

    public void setMsginfo(String msginfo) {
        this.msginfo = msginfo;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

}
